language: generic
os: linux
dist: bionic

addons:
  apt:
    sources:
    packages:
      - clang-6.0
      - xutils-dev
      - sshpass

env:
  global:
    - CC="clang-6.0"
    - CXX="clang++-6.0"

stages:
  - name: Test
  - name: Collect stats
    if: type in (api, cron)

jobs:
  include:
    - stage: Test
      name: Check script
      script:
        - python3 "scripts/src/run.py" --help
        - |
          if test -n "$SSHPASS"
          then
              git -C ./data ls-remote --heads "git@github.com:${TRAVIS_REPO_SLUG}.git"
          fi
      after_success:
        - true
    - stage: Collect stats
      name: Round 1

cache:
  directories:
    - /tmp/build-stats-cache

before_install:
  - git config --global advice.detachedHead false

install:
  - REPO_URL=$(git remote get-url origin)
  - git clone --depth=5 --branch='data' "$REPO_URL" ./data
  - git -C ./data config core.sshCommand
        'sshpass -ev -Passphrase ssh -i "$TRAVIS_BUILD_DIR/github.key" -F /dev/null'
  - chmod 0600 ./github.key

script:
  - python3 "scripts/src/run.py"
        --use-mason
        --deadline "$(date +%s -d '30 minutes')"
        --max-samples 15
        --since "2015-07-04"
        --source-repository "https://github.com/mapnik/mapnik.git"
        -- master v3.0.x

before_cache:
  # Keep only up to five most recent cache files.
  # Fewer files will be kept if the data branch clone is not deep enough.
  - |
    if git -C ./data log -5 --oneline
    then
        ls -1 /tmp/build-stats-cache/data_at_*.yml |
            grep -vFf <( git -C ./data log -5 "--format=data_at_%H.yml" ) |
            xargs -d '\n' rm -vf --
    fi

after_success:
  - |
    if test -n "$SSHPASS"
    then
        git -C ./data push -v "git@github.com:${TRAVIS_REPO_SLUG}.git"
    fi
